name: Create draft release

on:
  push:
    branches:
      - 'sdk-v[0-9]+.[0-9]+.[0-9]+*'
    tags:
      - 'sdk-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    name: Publish Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest tag
        id: latest-tag
        run: |
          echo "::set-output name=latest::$( git tag | sort -V | tail -1)"
      - name: Checkout branch "master"
        uses: actions/checkout@v3
        with:
          ref: 'master'
          fetch-depth: 0
      - name: Generate changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/ci/github/generate-changelog.sh ${{ steps.tags.outputs.latest-tag }} >>  Changelog.md
      - name: Create draft release
        id: create-draft-release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: SDK ${{ github.ref }}
          draft: true
          body_path: ./worker/scripts/changelog/release-notes.md
